### ISSUE TITLE
nacos服务重新注册上去报错

### ISSUE THREAD

**Issue by rlacjfjin** [nacos-group/nacos-sdk-python#112]
报错日志如下：
Exception in thread Thread-67793:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/iwms_algo/helper/regis_server.py", line 24, in printTime
    is_health = client.send_heartbeat("wms-algo", ip, "8080")
  File "/opt/conda/lib/python3.8/site-packages/nacos/client.py", line 1026, in send_heartbeat
    resp = self._do_sync_req("/nacos/v1/ns/instance/beat", None, params, None, self.default_timeout, "PUT")
  File "/opt/conda/lib/python3.8/site-packages/nacos/client.py", line 668, in _do_sync_req
    raise NacosRequestException("All server are not available")
nacos.exception.NacosRequestException: All server are not available

我重新注册的方式是：（包括第一次注册的时候）
  client.add_naming_instance(service_name="wms-algo", ip=ip, port=port, cluster_name="DEFAULT",
                             weight=1, metadata=None, enable=True, healthy=True, ephemeral=True)

不知道怎么解决，求助！
谢谢

**Comment by zepen** [comment]
找到原因了嘛？直接关闭了
