### ISSUE TITLE
get config error

### ISSUE THREAD

**Issue by jack-gits** [nacos-group/nacos-sdk-python#122]
遇到一个奇怪的错误

/Users/xuhao/opt/anaconda3-5.3.1/anaconda3/envs/pyth_3.7_ocr/bin/python /Users/xuhao/work/SourceCode/neuron-ocr/test/testdd.py
ERROR:nacos.client:[get-config] exception update expected at most 1 arguments, got 2 occur
Traceback (most recent call last):
  File "/Users/xuhao/opt/anaconda3-5.3.1/anaconda3/envs/pyth_3.7_ocr/lib/python3.7/site-packages/nacos/client.py", line 395, in get_config
    resp = self._do_sync_req("/nacos/v1/cs/configs", None, params, None, timeout or self.default_timeout)
  File "/Users/xuhao/opt/anaconda3-5.3.1/anaconda3/envs/pyth_3.7_ocr/lib/python3.7/site-packages/nacos/client.py", line 612, in _do_sync_req
    self._inject_version_info(all_headers)
  File "/Users/xuhao/opt/anaconda3-5.3.1/anaconda3/envs/pyth_3.7_ocr/lib/python3.7/site-packages/nacos/client.py", line 776, in _inject_version_info
    headers.update("User-Agent", "Nacos-Python-Client:v" + VERSION)
TypeError: update expected at most 1 arguments, got 2
ERROR:nacos.client:[get-config] get config from server failed, try snapshot, data_id:neuron-common.yml, group:neuron, namespace:dev1

**Comment by jack-gits** [comment]
VERSION是0.1.9

**Comment by xiaoFine** [comment]
`headers.update("User-Agent", "Nacos-Python-Client:v" + VERSION)`
headers是字典，update应该是这样写吧？
```
headers.update({"User-Agent":"Nacos-Python-Client:v" + VERSION})
```

**Comment by FantZero** [comment]
用0.1.8版本，0.1.9的有bug

**Comment by chenhao26-nineteen** [comment]
我们也遇到了，0.1.9这个bug感觉需要解一下

**Comment by bllli** [comment]
@jack-gits 看到 #120  0.1.10 版本已合并主分支,  有计划什么时候发布到 pypi 吗?

**Comment by rainmanliu** [comment]
他们这库有过 测试用例吗，灰度有没有，这是很基础的语法错误啊
