### ISSUE TITLE
publish_config方法，在 2.2.3 版本上报错没有权限

### ISSUE THREAD

**Issue by guangzhimen** [nacos-group/nacos-sdk-python#140]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nacos/client.py", line 386, in publish_config
    resp = self._do_sync_req("/nacos/v1/cs/configs", None, None, params,
  File "/usr/local/lib/python3.8/site-packages/nacos/client.py", line 682, in _do_sync_req
    resp = urlopen(req, timeout=timeout, context=ctx)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sora/Downloads/scripts/test.py", line 153, in <module>
    change_conf_temp("192.168.30.212", "192.168.30.213", "192.168.30.214")
  File "/Users/sora/Downloads/scripts/test.py", line 121, in change_conf_temp
    client.publish_config('cmdb.yaml', 'DEFAULT_GROUP', content, config_type='yaml')
  File "/usr/local/lib/python3.8/site-packages/nacos/client.py", line 394, in publish_config
    raise NacosException("Insufficient privilege.")
nacos.exception.NacosException: Insufficient privilege.

测试了get_config方法可以获取到配置，说明鉴权已经通过

代码：
client = NacosClient(server_addresses='http://192.168.30.212:8848', namespace='pre', username="xxxx", password="xxxxx")
#print(client.get_config('cmdb.yaml', 'DEFAULT_GROUP'))
with open('{}/nacos/appconf/cmdb.yaml'.format("/Users/sora/Downloads/redops"), 'r') as file:
    yaml_content = yaml.safe_load(file)
    content = yaml.dump(yaml_content)
client.publish_config('cmdb.yaml', 'DEFAULT_GROUP', content, config_type='yaml')

**Comment by CZJCC** [comment]
0.1.16 fixed
