### ISSUE TITLE
add_naming_instance 403 error

### ISSUE THREAD

**Issue by ccfuncy** [nacos-group/nacos-sdk-python#141]
在Nacos开启ak/sk鉴权后，`add_naming_instance` 会报403错误。
```
Traceback (most recent call last):
  File "main.py", line 199, in <module>
    client.add_naming_instance("fcyt-alig", container_ip, "8001",cluster_name=cluster_name,ephemeral=False)
  File "/usr/local/lib/python3.8/dist-packages/nacos/client.py", line 813, in add_naming_instance
    raise NacosException("Insufficient privilege.")
nacos.exception.NacosException: Insufficient privilege.
```

**Comment by CZJCC** [comment]
0.1.16 fixed
