### ISSUE TITLE
nacos注册报错

### ISSUE THREAD

**Issue by huyang19881115** [nacos-group/nacos-sdk-python#153]
Traceback (most recent call last):
File "/data/llmservice-province/langchain_province/api.py", line 2174, in <module>
regServer()
File "/data/llmservice-province/langchain_province/api.py", line 1971, in regServer
client.add_naming_instance(service_name=ServerName,
File "/data/llmservice-province/langchain_province/nacos/client.py", line 898, in add_naming_instance
resp = self._do_sync_req("/nacos/v1/ns/instance", {"example":"example"}, None, params, self.default_timeout, "POST", "naming")
File "/data/llmservice-province/langchain_province/nacos/client.py", line 702, in _do_sync_req
raise NacosRequestException("All server are not available")
nacos.exception.NacosRequestException: All server are not available

**Comment by huyang19881115** [comment]
目前出现的问题，是nacos 启动后，会保留注册服务的信息，一直不掉。把nacos 的日志清理掉，就可以注册上去了，比较奇怪，不知道那个注册信息再日志的那块位置？

**Comment by GululuCopa** [comment]
碰到了相同的问题，苦比的是无权限清理nacos日志，目前不知道咋整了

**Comment by Ricco567** [comment]
请问这个问题怎么解决的啊，怎么清理nacos的日志
