### ISSUE TITLE
add_config_watcher ERROR

### ISSUE THREAD

**Issue by wangzihchao** [nacos-group/nacos-sdk-python#172]
python code：
def nacos_call_back(content):
    print("nacos_call_back run")

if __name__ == '__main__':
    client = nacos.NacosClient(server_addresses=server_addresses, namespace=namespace, username=user_name,
                               password=password);
    custom_config = client.get_config(data_id=dataId, group=group)
    result = yaml.load(custom_config, Loader=yaml.FullLoader)
    print(result, type(result))
    print(result)
    client.send_heartbeat()
    custom_thread = threading.Thread(
        target=client.add_config_watcher(data_id=data_id,
                                         group=group,
                                         cb=nacos_call_back))
    custom_thread.start()

报错信息：
Exception in thread Thread-15 (_do_pulling):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 328, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [WinError 109] 管道已结束。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\learn\code\flasklearn\pythonProject\.venv\Lib\site-packages\nacos\client.py", line 746, in _do_pulling

有人遇到过这个问题吗

**Comment by CZJCC** [comment]
看看最新版本0.1.17有没有这个问题，另外也不需要在配置的场景下send_heartbeat

**Comment by wangzihchao** [comment]
> client.send_heartbeat()

用的版本就是0.1.17

**Comment by CZJCC** [comment]
0.1.17版本746行是这个，跟你的堆栈对不上
https://github.com/nacos-group/nacos-sdk-python/blob/ebe30647e3d9f5511f5ce4c76d79936b38401510/nacos/client.py#L746C1-L747C1

**Comment by wangzihchao** [comment]
我复制过来哈
![image](https://github.com/user-attachments/assets/5f9af7b6-31eb-4f8e-bf94-fe98ecb40fb9)
Exception in thread Thread-15 (_do_pulling):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 328, in _recv_bytes
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [WinError 109] 管道已结束。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner

**Comment by CZJCC** [comment]
SERVER_ADDRESSES = ""
NAMESPACE = ""
USERNAME = ''
PASSWORD = ''


def main():
    d = "test"
    g = "DEFAULT_GROUP"

    def nacos_call_back(content):
        print("nacos_call_back run")

    client = nacos.NacosClient(server_addresses=SERVER_ADDRESSES, namespace=NAMESPACE, username=USERNAME,
                               password=PASSWORD)
    custom_config = client.get_config(data_id=d, group=g)
    result = yaml.load(custom_config, Loader=yaml.FullLoader)
    print(result, type(result))
    print(result)
    custom_thread = threading.Thread(
        target=client.add_config_watcher(data_id=d,
                                         group=g,
                                         cb=nacos_call_back))
    custom_thread.start()
    while True:
        time.sleep(1)

if __name__ == '__main__':
    main()         用这段代码测试下看看

**Comment by wangzihchao** [comment]
可以了，成功监听到了配置的变化，请问这是因为子线程已经结束了导致的吗，还有就是必须在主线程一直等待吗

**Comment by CZJCC** [comment]
不sleep的话，你主线程会退出了呀

**Comment by wangzihchao** [comment]
了解了，谢谢
