### ISSUE TITLE
使用ctrl+c强制退出时，_process_polling_result无法处理异常

### ISSUE THREAD

**Issue by 123456yzj** [nacos-group/nacos-sdk-python#195]
`Traceback (most recent call last):
  File "d:\project\tailin\dev\crawler\.conda\Lib\multiprocessing\connection.py", line 328, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [WinError 109] 管道已结束。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\project\tailin\dev\crawler\.conda\Lib\site-packages\nacos\client.py", line 818, in _process_polling_result
    cache_key, content, md5 = self.notify_queue.get()
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\project\tailin\dev\crawler\.conda\Lib\multiprocessing\queues.py", line 103, in get
    res = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "d:\project\tailin\dev\crawler\.conda\Lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\project\tailin\dev\crawler\.conda\Lib\multiprocessing\connection.py", line 337, in _recv_bytes
    raise EOFError
EOFError`

主动关闭主进程后， self.notify_queue，无法与主进程通信抛出异常。但是未做处理
怎么自己的代码中在生成对象后，遇到ctrl+c时处理这个错误呢

**Comment by PterX** [comment]
https://github.com/nacos-group/nacos-sdk-python/blob/ec2d037a969f27b6e909f8975dff919c78d80873/nacos/client.py#L812
这个地方主动拉取的线程不受管控导致，应该放入client，在stop watch的时候结束掉
